### PR TITLE
Update 6.5.md

### PR DESCRIPTION
**Pull request by zhenorzz**
bug

### CODE REVIEW

**Comment by walkccc** [comment]
I think this is not correct. Could you plz provide some explanations? The answer is originated from the Instructor's Manual. Anyway, thank you very much since there was a typo and I've corrected it.

**Comment by zhenorzz** [comment]
I am not good at English. When you use A[i] in while loop, A[i] will be changed with his parent (A[i] = A[PARENT(i)]). In the next Comparison, while A[PARENT(i)] < A[i] must be false.

**Comment by zhenorzz** [comment]
Let's do A=[4,2,3,1],  HEAP-INCREASE-KEY(A, 4, 10).
Firstly, 
A[4] = 10
while A[parent(i)] < A[i]  ->  while 2 < 10,   true
A[i] = A[parent(i)]  ->  A[4] = 2
i = PARENT(i)  ->  2

secend,
while A[parent(i)] < A[i]  ->  while 4 < 2, false,  because the previous loop not change the parent.
next,
A[i]=key -> A[2] = 10
the Array will be [4,10,3,2]

**Comment by walkccc** [comment]
Nice job! I deliberately thought again. You are right! Plz check the page again. Thank you! 😊 
Btw, the typo: 'l' -> '1'.

**Comment by zhenorzz** [comment]
I am so excited you can catch what I said. Because it is hard to change my thought in English and write it in. I am good at reading except writing.

**Pull request merged**
