### PR TITLE
Update 17.4

### PR DESCRIPTION
**Pull request by JingqingLin**

### CODE REVIEW

**Comment by walkccc** [comment]
Thank you!

**Comment by walkccc** [comment]
Well, I think it should be \alpha_{i - 1}.
I corrected it on the latest master. Thanks.

**Comment by JingqingLin** [comment]
> 
> 
> Well, I think it should be \alpha_{i - 1}.
> I corrected it on the latest master. Thanks.

您好，不知您是否方便使用中文。$\alpha_{i - 1} \ge 1 / 2$ 是题目给出的条件，我认为应该对第 i 次操作进行讨论。

**Comment by walkccc** [comment]
可以，用英文只是希望大家都看的懂。

仔細想想你說的對，對 i 進行討論才不失一般性，我明天再更新回來。

謝謝你的回覆🙏

**Comment by walkccc** [comment]
Updated. Please help check it.

**Comment by JingqingLin** [comment]
> 
> 
> Updated. Please help check it.

👍 Appreciate your hard work.

**Pull request merged**
