### PR TITLE
Fix some typos, write another possible solution for 6.5-8, add 15.3-2 picture

### PR DESCRIPTION
**Pull request by nienjen**

### CODE REVIEW

**Comment by walkccc** [comment]
Hey friend. Could you plz open each PR in a separate one?
I'd like to keep each commit message much more specific :)
Thank you.

**Comment by walkccc** [comment]
Hi @nienjen, I mean, instead of putting all PRs in here, you can open a new PR for each update so that I can review each PR one by one. Thank you for your patient!

**Comment by nienjen** [comment]
I'm going to separate the pull requests soon :)

**Comment by walkccc** [comment]
Maybe I'll update the README.md to indicate this soon. Again, thank you very much for following this pattern. Your contribution always makes this crowd-work open-source better 👍

**Pull request closed without merging**
