### PR TITLE
Update 15.2.md

### PR DESCRIPTION
**Pull request by iBug**
Missing sum item in one formula here:

image

### CODE REVIEW

**Comment by walkccc** [comment]
Thank you!

**Comment by yc-zc** [comment]
Lol I nearly thought you are an ANU student too

**Comment by iBug** [comment]
@yc-zc Pardon but what is an ANU student?

**Comment by yc-zc** [comment]
> @yc-zc Pardon but what is an ANU student?

Lol, ANU is Australian No-internet University. Our latest assignment of algorithm is about 15-12, that's why I found this repo.

**Pull request merged**
